### PR TITLE
fix: Check for window being available prior to relying on it

### PR DESCRIPTION
**Pull request by joostdecock**
Closes https://github.com/vasturiano/force-graph/issues/214

Obviously, this is merely a proposal. But I hope it gets the idea across.

### CODE REVIEW

**Comment by vasturiano** [comment]
@joostdecock thanks for creating this PR, and opening this discussion.

Tbh I'm not certain this is not a problematic approach however. This component is not currently SSR compatible, and making it so actually involves a much larger overhaul of the code, even in what's related to its sub-dependencies out of which some might also not be SSR compatible.

Atm, access to the `window` object is essential for a proper setup of the component, like setting the canvas pixel ratio and computing offsets for correct dragging interactions.  And setting guessed default values for these is bound to cause some problems. Specially since the code that detects if the running environment is the browser is only ran at import time, thus will not be able to recover from it when the app code is finally passed to the browser.

Generally these type of issues are solved by bypassing SSR processing in your app for certain components (such as `force-graph`) which rely on browser-only items like `window`. This is quite common in SSR frameworks like `nextjs` for example. Have you tried this approach, and is there a reason why that's not possible in your case?

**Comment by joostdecock** [comment]
Thank you for the feedback, and pardon my naive approach. I just wanted to try and do something helpful rather than just complain :)

As far as SSR goes, I am using Gatsby in this project, and while I can certainly keep the component that uses this code from being rendered in SSR, that doesn't do any good, since the code already errors out on `import`.

I'm certainly willing to try and find ways to work around it. Perhaps I can put this in an CJS-style file where I can use a conditional `require` instead :thinking: 

I'll see what I can come up with.

**Comment by vasturiano** [comment]
@joostdecock in `nextjs` there is a way to dynamically import modules, to tackle this issue exactly: https://nextjs.org/docs/advanced-features/dynamic-import

Does Gatsby offer a similar dynamic import feature perhaps?

**Comment by joostdecock** [comment]
Turns out it does (you learn something every day). Here's what I used that works, sharing it here in case people end up here Googling a similar question:

```js
const MyGraphComponent = props => { 
  const [ForceGraph, setForceGraph] = useState(false)

  useEffect(() => {
    // ForceGraph will break SSR, and needs to be loaded dynamically
    async function importForceGraphModule() {
      const fg = (await import('react-force-graph-2d'))
      setForceGraph(fg.default)
    }
    importForceGraphModule()
  }, [])

  return ForceGraph
    ? <ForceGraph ... />
    : <p>Loading graph</p>
}
```

I used state here as a simply way to trigger a re-render after the library is loaded. YMMV

Thank you for the help, much appreciated @vasturiano :pray:

**Pull request closed without merging**
