### PR TITLE
Add new render method: pushParticle

### PR DESCRIPTION
**Pull request by tinchoz49**
This is related with: https://github.com/vasturiano/force-graph/issues/54

It adds a new method: `pushParticle(source, target, { speed, color, width })`

I added a new example to show how it works.

### CODE REVIEW

**Comment by vasturiano** [comment]
Thanks for this PR @tinchoz49, it's a neat idea. 👍 
I've refactored things up a bit and simplified the api into a single param that inherits the styling from the existing particle props, so it became: `.emitParticle(link)`.

**Comment by tinchoz49** [comment]
that's great!! thanks!

**Comment by alexmittsel** [comment]
How can i initialize particle color? I think current solution does not allow set color what i need

**Comment by vasturiano** [comment]
@alexmittsel it follows the logic applied to `linkDirectionalParticleColor`.

**Comment by alexmittsel** [comment]
@vasturiano Thanks!

**Pull request merged**
